"""Audit models for the trading system.

This module defines the core data structures for the audit logging system:
- AuditEventType: Types of events that can be audited
- ActorType: Types of actors that can generate events
- AuditSeverity: Event severity levels (INFO, WARNING, CRITICAL)
- ResourceType: Types of resources that can be affected by events
- EventSource: Sources from which events can originate
- ValueMode: How values are recorded in audit events
- AuditEvent: Immutable event representing an audit occurrence
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from uuid import UUID


class AuditEventType(str, Enum):
    """Types of audit events that can be generated by the system.

    Order events:
        ORDER_PLACED: An order was placed
        ORDER_ACKNOWLEDGED: An order was acknowledged by the broker
        ORDER_FILLED: An order was filled
        ORDER_CANCELLED: An order was cancelled
        ORDER_REJECTED: An order was rejected

    Config events:
        CONFIG_CREATED: A configuration was created
        CONFIG_UPDATED: A configuration was updated
        CONFIG_DELETED: A configuration was deleted

    Alert events:
        ALERT_EMITTED: An alert was emitted
        ALERT_ACKNOWLEDGED: An alert was acknowledged
        ALERT_RESOLVED: An alert was resolved

    System events:
        SYSTEM_STARTED: The system was started
        SYSTEM_STOPPED: The system was stopped
        HEALTH_CHANGED: Health status changed

    Security events:
        AUTH_LOGIN: User logged in
        AUTH_LOGOUT: User logged out
        AUTH_FAILED: Authentication failed
        PERMISSION_CHANGED: Permissions were changed
    """

    # Order events
    ORDER_PLACED = "order_placed"
    ORDER_ACKNOWLEDGED = "order_acknowledged"
    ORDER_FILLED = "order_filled"
    ORDER_CANCELLED = "order_cancelled"
    ORDER_REJECTED = "order_rejected"

    # Config events
    CONFIG_CREATED = "config_created"
    CONFIG_UPDATED = "config_updated"
    CONFIG_DELETED = "config_deleted"

    # Alert events
    ALERT_EMITTED = "alert_emitted"
    ALERT_ACKNOWLEDGED = "alert_acknowledged"
    ALERT_RESOLVED = "alert_resolved"

    # System events
    SYSTEM_STARTED = "system_started"
    SYSTEM_STOPPED = "system_stopped"
    HEALTH_CHANGED = "health_changed"

    # Security events
    AUTH_LOGIN = "auth_login"
    AUTH_LOGOUT = "auth_logout"
    AUTH_FAILED = "auth_failed"
    PERMISSION_CHANGED = "permission_changed"


class ActorType(str, Enum):
    """Types of actors that can generate audit events.

    USER: Human user interacting with the system
    SYSTEM: Automated system process
    API: External API client
    SCHEDULER: Scheduled job or cron task
    """

    USER = "user"
    SYSTEM = "system"
    API = "api"
    SCHEDULER = "scheduler"


class AuditSeverity(str, Enum):
    """Audit event severity levels.

    INFO: Routine informational event
    WARNING: Potential issue that should be monitored
    CRITICAL: Serious issue requiring immediate attention
    """

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class ResourceType(str, Enum):
    """Types of resources that can be affected by audit events.

    ORDER: Trading order
    POSITION: Trading position
    CONFIG: Configuration settings
    ALERT: Alert definition or instance
    STRATEGY: Trading strategy
    ACCOUNT: Trading account
    PERMISSION: Access permission
    SESSION: User session
    """

    ORDER = "order"
    POSITION = "position"
    CONFIG = "config"
    ALERT = "alert"
    STRATEGY = "strategy"
    ACCOUNT = "account"
    PERMISSION = "permission"
    SESSION = "session"


class EventSource(str, Enum):
    """Sources from which audit events can originate.

    WEB: Web browser interface
    API: REST API
    WORKER: Background worker process
    SCHEDULER: Scheduled task
    SYSTEM: Internal system process
    CLI: Command line interface
    """

    WEB = "web"
    API = "api"
    WORKER = "worker"
    SCHEDULER = "scheduler"
    SYSTEM = "system"
    CLI = "cli"


class ValueMode(str, Enum):
    """How values are recorded in audit events.

    DIFF: Record old and new values for changes
    SNAPSHOT: Record complete state at point in time
    REFERENCE: Record reference/pointer to stored value
    """

    DIFF = "diff"
    SNAPSHOT = "snapshot"
    REFERENCE = "reference"


@dataclass(frozen=True)
class AuditEvent:
    """Immutable event representing an audit occurrence.

    AuditEvent is the core data structure for the audit logging system.
    It captures what happened, when, who did it, and what was affected.

    Attributes:
        event_id: Unique identifier for this audit event
        timestamp: When the event occurred (UTC)
        event_type: Classification of the event
        severity: How critical the event is

        actor_id: Identifier of the actor who caused the event
        actor_type: Type of the actor (USER, SYSTEM, etc.)
        actor_display: Human-readable name for the actor
        impersonator_id: If impersonating, the original actor's ID

        resource_type: Type of resource affected
        resource_id: Identifier of the affected resource

        value_mode: How values are recorded (DIFF, SNAPSHOT, REFERENCE)
        old_value: Previous state (for updates/deletes)
        new_value: New state (for creates/updates)
        value_hash: Hash of the values for integrity checking

        request_id: Identifier linking to the originating request
        trace_id: Distributed tracing identifier
        correlation_id: Correlation ID for related events
        source: Where the event originated from

        client_ip: Client IP address if available
        user_agent: Client user agent if available

        environment: Deployment environment (dev, staging, production)
        service: Name of the service that generated the event
        version: Version of the service

        schema_version: Version of the audit event schema
        metadata: Additional arbitrary data
    """

    # Core identity (required)
    event_id: UUID
    timestamp: datetime  # UTC

    # Event classification (required)
    event_type: AuditEventType
    severity: AuditSeverity

    # Actor (required)
    actor_id: str
    actor_type: ActorType

    # Resource (required)
    resource_type: ResourceType
    resource_id: str

    # Correlation (required)
    request_id: str
    source: EventSource

    # Environment (required)
    environment: str
    service: str
    version: str

    # Actor (optional)
    actor_display: str | None = None
    impersonator_id: str | None = None

    # Values (optional with defaults)
    value_mode: ValueMode = ValueMode.DIFF
    old_value: dict | None = None
    new_value: dict | None = None
    value_hash: str | None = None

    # Correlation (optional)
    trace_id: str | None = None
    correlation_id: str | None = None

    # Client info (optional)
    client_ip: str | None = None
    user_agent: str | None = None

    # Metadata (optional with defaults)
    schema_version: int = 1
    metadata: dict | None = None
