"""Alert models for the trading system.

This module defines the core data structures for the alert system:
- AlertType: Types of alerts that can be generated
- Severity: Alert severity levels (SEV1=Critical, SEV2=Warning, SEV3=Info)
- EntityRef: Reference to trading entities (account, symbol, strategy, run)
- AlertEvent: Immutable event representing an alert occurrence
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from uuid import UUID

# Type alias for JSON-serializable scalar values
JsonScalar = str | int | float | bool | None


class AlertType(str, Enum):
    """Types of alerts that can be generated by the system.

    Trading alerts:
        ORDER_REJECTED: An order was rejected by the broker
        ORDER_FILLED: An order was filled (informational)
        POSITION_LIMIT_HIT: Position size limit reached
        DAILY_LOSS_LIMIT: Daily loss limit breached
        KILL_SWITCH_ACTIVATED: Emergency trading halt triggered

    System alerts:
        COMPONENT_UNHEALTHY: A system component is degraded or down
        COMPONENT_RECOVERED: A previously unhealthy component recovered
        DB_WRITE_FAIL: Database write operation failed
        STORAGE_THRESHOLD: Storage usage exceeded threshold
        ALERT_DELIVERY_FAILED: Failed to deliver an alert notification
    """

    # Trading alerts
    ORDER_REJECTED = "order_rejected"
    ORDER_FILLED = "order_filled"
    POSITION_LIMIT_HIT = "position_limit_hit"
    DAILY_LOSS_LIMIT = "daily_loss_limit"
    KILL_SWITCH_ACTIVATED = "kill_switch_activated"

    # System alerts
    COMPONENT_UNHEALTHY = "component_unhealthy"
    COMPONENT_RECOVERED = "component_recovered"
    DB_WRITE_FAIL = "db_write_fail"
    STORAGE_THRESHOLD = "storage_threshold"
    ALERT_DELIVERY_FAILED = "alert_delivery_failed"


class Severity(int, Enum):
    """Alert severity levels.

    SEV1 (Critical): Immediate attention required, trading may be impacted
    SEV2 (Warning): Potential issue that should be investigated
    SEV3 (Info): Informational alert, no action required
    """

    SEV1 = 1  # Critical
    SEV2 = 2  # Warning
    SEV3 = 3  # Info


# Alert types that represent recovery from a previous alert
RECOVERY_TYPES: frozenset[AlertType] = frozenset({AlertType.COMPONENT_RECOVERED})


@dataclass(frozen=True)
class EntityRef:
    """Reference to trading entities associated with an alert.

    All fields are optional since not every alert relates to every entity type.
    For example, a system health alert may not have a symbol or strategy.

    Attributes:
        account_id: Trading account identifier
        symbol: Ticker symbol (e.g., "AAPL")
        strategy_id: Strategy identifier
        run_id: Strategy run identifier
    """

    account_id: str | None = None
    symbol: str | None = None
    strategy_id: str | None = None
    run_id: str | None = None


@dataclass(frozen=True)
class AlertEvent:
    """Immutable event representing an alert occurrence.

    AlertEvent is the core data structure passed through the alert pipeline.
    It captures what happened, when, where, and with what severity.

    Attributes:
        alert_id: Unique identifier for this alert instance
        type: The type of alert
        severity: How critical the alert is
        event_timestamp: When the alert occurred
        fingerprint: Deduplication key for grouping related alerts
        entity_ref: Optional reference to related trading entities
        summary: Human-readable one-line summary
        details: Additional structured data about the alert
    """

    alert_id: UUID
    type: AlertType
    severity: Severity
    event_timestamp: datetime
    fingerprint: str
    entity_ref: EntityRef | None
    summary: str
    details: dict[str, JsonScalar] = field(default_factory=dict)
